### ISSUE TITLE
Add FAQ

### ISSUE THREAD

**Issue by scottrigby** [weaveworks/weave-gitops-docs#49]
See writing from earlier collab and meeting with Paul below in [this Google doc](https://docs.google.com/document/d/1Lw8K-xQgWL1DPIUUzih5ri7a2yi-2Vf3Tk7gHmP3kCI/edit#)

- Outline
- Work on first version of publishable content

See #39

**Comment by pzfreo** [comment]
I think this should be handled elsewhere.
